# Annnonce 
# -----------------

# Envoyer un message aléaoire ? (true ou false)
random-order: false

# Temps entre chaques messages (en minutes) ?
message-delay: 15

# Prefix dans chaque message ?
message-prefix: '&c[Annonce] '

 
  
# MySQL 
# -----------------

# Info de connexion
database:
  address: localhost
  port: 3306
  name: V6_bungee_yamtmp
  username: bungee
  password: SxN7VU9XzeOw5jYj
  table-prefix: yamtmp_
